spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carhired?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  data:
    redis:
      host: "redis"
      port: 6379