CREATE TABLE automakers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted    BOOLEAN                                 NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    country    VARCHAR(100),
    CONSTRAINT pk_automakers PRIMARY KEY (id)
);

CREATE TABLE models
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted_at   TIMESTAMP WITHOUT TIME ZONE,
    deleted      BOOLEAN                                 NOT NULL,
    name         VARCHAR(100)                            NOT NULL,
    released_at  date,
    automaker_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_models PRIMARY KEY (id)
);

CREATE TABLE rentals
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN                                 NOT NULL,
    due_date    date                                    NOT NULL,
    return_date date,
    vehicle_id  BIGINT                                  NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_rentals PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        CHAR,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted_at  TIMESTAMP WITHOUT TIME ZONE,
    deleted     BOOLEAN                                 NOT NULL,
    email       VARCHAR(100)                            NOT NULL,
    password    VARCHAR(100)                            NOT NULL,
    picture_uri VARCHAR(255),
    role        VARCHAR(255)                            NOT NULL,
    name        VARCHAR(100)                            NOT NULL,
    cpf         VARCHAR(11)                             NOT NULL,
    phone       VARCHAR(20),
    address     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vehicles
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted_at     TIMESTAMP WITHOUT TIME ZONE,
    deleted        BOOLEAN                                 NOT NULL,
    license_plaque VARCHAR(7)                              NOT NULL,
    color          VARCHAR(50)                             NOT NULL,
    num_doors      SMALLINT                                NOT NULL,
    mileage        INTEGER                                 NOT NULL,
    renavam        VARCHAR(11)                             NOT NULL,
    chassis        VARCHAR(17)                             NOT NULL,
    rent_price     DECIMAL(17, 2)                          NOT NULL,
    available      BOOLEAN                                 NOT NULL,
    model_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);

ALTER TABLE automakers
    ADD CONSTRAINT uc_automakers_name UNIQUE (name);

ALTER TABLE models
    ADD CONSTRAINT uc_models_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_cpf UNIQUE (cpf);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_picture_uri UNIQUE (picture_uri);

ALTER TABLE vehicles
    ADD CONSTRAINT uc_vehicles_chassis UNIQUE (chassis);

ALTER TABLE vehicles
    ADD CONSTRAINT uc_vehicles_license_plaque UNIQUE (license_plaque);

ALTER TABLE vehicles
    ADD CONSTRAINT uc_vehicles_renavam UNIQUE (renavam);

ALTER TABLE models
    ADD CONSTRAINT FK_MODELS_ON_AUTOMAKER FOREIGN KEY (automaker_id) REFERENCES automakers (id);

ALTER TABLE rentals
    ADD CONSTRAINT FK_RENTALS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES users (id);

ALTER TABLE rentals
    ADD CONSTRAINT FK_RENTALS_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);

ALTER TABLE vehicles
    ADD CONSTRAINT FK_VEHICLES_ON_MODEL FOREIGN KEY (model_id) REFERENCES models (id);